import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { getContactsApi } from './contactApis';

export interface Contact {
    id: number;
    first_name: string;
    last_name?: string;
    gender?: 'Male' | 'Female' | 'Other';
    email: string;
    department?: 'Marketing' | 'Sales' | 'IT' | 'Support';
    contribution?: number;
    active?: boolean;
    avatar?: string;
}

export interface ContactsState {
    value: Array<Contact> | [];
    status: 'idle' | 'loading' | 'failed';
}

const initialState: ContactsState = {
    value: [],
    status: 'idle',
};

export const getContactsAsync = createAsyncThunk(
    'counter/getContacts',
    async () => {
        const response: any = await getContactsApi();
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const contactsSlice = createSlice({
    name: 'contacts',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setContactsList: (state, action) => {
            return {
                ...state,
                value: action.payload
            }
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getContactsAsync.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(getContactsAsync.fulfilled, (state, action) => {
                state.status = 'idle';
                state.value = action.payload;
            })
            .addCase(getContactsAsync.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

export const selectContacts = (state: RootState) => state.ContactsReducer.value;
export const contactsAsyncStatus = (state: RootState) => state.ContactsReducer.status;


export default contactsSlice.reducer;